### PR TITLE
feature: support between operator in query

### PR DESCRIPTION
**Pull request by vnmylove**
add more operator between  to support query with between in NodeJs

### CODE REVIEW

**Comment by sajov** [comment]
Thanks

**Comment by vnmylove** [comment]
Hi
Yes, i know i can use $gte and $lte but i think the between operator easy to write/read.
Deveopers need only write:
query ={
     property: {$between:[val1,val2]}
}
But with $lte and $gte :
query ={
     property: {$gte: val1},
     property: {$lte: val2}
}
My developers ask me why do they have to use $lte and $gte for between. Its not friendly for write/read. 
Ok. Its up to you but i wonder why can’t you give developers one more option. They can use which one they like
Thanks

**Comment by sajov** [comment]
Sure I will merge this. But keep in mind that we have to whitelist Special params in füttere. I have read it somewhere about Feathers-QueryParser 
Thx

**Comment by sajov** [comment]
Hi
i added feature $between
[see tests](https://github.com/sajov/feathers-solr/blob/master/test/adapter.test.js#L502)

**Pull request closed without merging**
